#!/usr/bin/env bash

set -uexo pipefail

# Files

cp -arfT files/etc /etc
cp -arfT files/usr /usr

# Packages

dnf -y install \
    xiaomi-davinci-firmware \
    alsa-ucm-conf-sm7150 \
    ath10k-shutdown \
    tqftpserv \
    qbootctl \
    rmtfs \
    qrtr \
    pd-mapper \
    bootmac

# Services

systemctl enable \
    tqftpserv.service \
    rmtfs.service \
    qbootctl.service \
    bootmac-bluetooth.service

# Kernel

mkdir -p /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-headers
rm -rf /usr/lib/modules/*
dnf -y install kernel
rm -r /boot/dtb
